// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: desired.proto

package desiredpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_PushDesired_FullMethodName = "/nanokube.desired.v1.Agent/PushDesired"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent is the gRPC service nanokube-agent exposes. The operator (in
// steady state) or the CLI (bootstrap/break-glass) is the client; the
// agent never initiates contact. Step 1 runs this dev-grade (plaintext
// or self-signed) — mTLS/PKI hardening is Step 5.
type AgentClient interface {
	// PushDesired delivers a new desired document for the agent to apply:
	// blob sha256 verification, confext placement + refresh, then
	// bookkeeping, in that order (see internal/ddi and the agent's own
	// apply pipeline). Idempotent: pushing a Desired whose name matches
	// what's already applied is a no-op success.
	PushDesired(ctx context.Context, in *Desired, opts ...grpc.CallOption) (*PushDesiredResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) PushDesired(ctx context.Context, in *Desired, opts ...grpc.CallOption) (*PushDesiredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushDesiredResponse)
	err := c.cc.Invoke(ctx, Agent_PushDesired_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
//
// Agent is the gRPC service nanokube-agent exposes. The operator (in
// steady state) or the CLI (bootstrap/break-glass) is the client; the
// agent never initiates contact. Step 1 runs this dev-grade (plaintext
// or self-signed) — mTLS/PKI hardening is Step 5.
type AgentServer interface {
	// PushDesired delivers a new desired document for the agent to apply:
	// blob sha256 verification, confext placement + refresh, then
	// bookkeeping, in that order (see internal/ddi and the agent's own
	// apply pipeline). Idempotent: pushing a Desired whose name matches
	// what's already applied is a no-op success.
	PushDesired(context.Context, *Desired) (*PushDesiredResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) PushDesired(context.Context, *Desired) (*PushDesiredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushDesired not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_PushDesired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Desired)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PushDesired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PushDesired_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PushDesired(ctx, req.(*Desired))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanokube.desired.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushDesired",
			Handler:    _Agent_PushDesired_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desired.proto",
}
