// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: desired.proto

package desiredpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Desired is the per-node desired document: rendered config (as a confext
// DDI blob) and the target OS image digest, applied together as one atom.
// See docs/nanokube/2026-07-06-nanokube-component-architecture-rev5.md,
// "desired は一枚のドキュメント".
type Desired struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the confext version name: a content hash of the rendered
	// manifest (file list) that produced blob. Excludes target_image_digest
	// so an image-only update does not trigger a DDI rebuild — see
	// internal/render.Desired.Name().
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// target_image_digest is the bootc image this config is meant to run
	// under, applied alongside blob as part of the same atomic document.
	// Not part of name's hash.
	TargetImageDigest string `protobuf:"bytes,2,opt,name=target_image_digest,json=targetImageDigest,proto3" json:"target_image_digest,omitempty"`
	// blob_sha256 is the sha256 of blob, for transport integrity
	// verification independent of any dm-verity signature.
	BlobSha256 string `protobuf:"bytes,3,opt,name=blob_sha256,json=blobSha256,proto3" json:"blob_sha256,omitempty"`
	// blob is the confext DDI (.raw) byte content, carried over gRPC.
	Blob          []byte `protobuf:"bytes,4,opt,name=blob,proto3" json:"blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Desired) Reset() {
	*x = Desired{}
	mi := &file_desired_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Desired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Desired) ProtoMessage() {}

func (x *Desired) ProtoReflect() protoreflect.Message {
	mi := &file_desired_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Desired.ProtoReflect.Descriptor instead.
func (*Desired) Descriptor() ([]byte, []int) {
	return file_desired_proto_rawDescGZIP(), []int{0}
}

func (x *Desired) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Desired) GetTargetImageDigest() string {
	if x != nil {
		return x.TargetImageDigest
	}
	return ""
}

func (x *Desired) GetBlobSha256() string {
	if x != nil {
		return x.BlobSha256
	}
	return ""
}

func (x *Desired) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

// DesiredMetadata mirrors Desired without the blob payload. It is the
// wire format for the <name>.json sidecar that sits next to <name>.raw
// on disk (in contract/fixtures/ and in the agent's bookkeeping) — small
// enough to inspect/diff, while the blob lives separately as the .raw
// file or travels over gRPC as Desired.blob.
type DesiredMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TargetImageDigest string                 `protobuf:"bytes,2,opt,name=target_image_digest,json=targetImageDigest,proto3" json:"target_image_digest,omitempty"`
	BlobSha256        string                 `protobuf:"bytes,3,opt,name=blob_sha256,json=blobSha256,proto3" json:"blob_sha256,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DesiredMetadata) Reset() {
	*x = DesiredMetadata{}
	mi := &file_desired_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredMetadata) ProtoMessage() {}

func (x *DesiredMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_desired_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredMetadata.ProtoReflect.Descriptor instead.
func (*DesiredMetadata) Descriptor() ([]byte, []int) {
	return file_desired_proto_rawDescGZIP(), []int{1}
}

func (x *DesiredMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DesiredMetadata) GetTargetImageDigest() string {
	if x != nil {
		return x.TargetImageDigest
	}
	return ""
}

func (x *DesiredMetadata) GetBlobSha256() string {
	if x != nil {
		return x.BlobSha256
	}
	return ""
}

var File_desired_proto protoreflect.FileDescriptor

const file_desired_proto_rawDesc = "" +
	"\n" +
	"\rdesired.proto\x12\x13nanokube.desired.v1\"\x82\x01\n" +
	"\aDesired\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x13target_image_digest\x18\x02 \x01(\tR\x11targetImageDigest\x12\x1f\n" +
	"\vblob_sha256\x18\x03 \x01(\tR\n" +
	"blobSha256\x12\x12\n" +
	"\x04blob\x18\x04 \x01(\fR\x04blob\"v\n" +
	"\x0fDesiredMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x13target_image_digest\x18\x02 \x01(\tR\x11targetImageDigest\x12\x1f\n" +
	"\vblob_sha256\x18\x03 \x01(\tR\n" +
	"blobSha256B5Z3github.com/MatchaScript/nanokube/contract/desiredpbb\x06proto3"

var (
	file_desired_proto_rawDescOnce sync.Once
	file_desired_proto_rawDescData []byte
)

func file_desired_proto_rawDescGZIP() []byte {
	file_desired_proto_rawDescOnce.Do(func() {
		file_desired_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desired_proto_rawDesc), len(file_desired_proto_rawDesc)))
	})
	return file_desired_proto_rawDescData
}

var file_desired_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_desired_proto_goTypes = []any{
	(*Desired)(nil),         // 0: nanokube.desired.v1.Desired
	(*DesiredMetadata)(nil), // 1: nanokube.desired.v1.DesiredMetadata
}
var file_desired_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_desired_proto_init() }
func file_desired_proto_init() {
	if File_desired_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desired_proto_rawDesc), len(file_desired_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_desired_proto_goTypes,
		DependencyIndexes: file_desired_proto_depIdxs,
		MessageInfos:      file_desired_proto_msgTypes,
	}.Build()
	File_desired_proto = out.File
	file_desired_proto_goTypes = nil
	file_desired_proto_depIdxs = nil
}
